spring.main.allow-bean-definition-overriding=true

spring.datasource.hikari.pool-name= CAGL-APZBANKING


#externalPropFile.path=$HOME/application-properties/application.properties
#dbProperties.path=$HOME/database-properties/database.properties

server.port=9286
server.context.path=/appzillonbankingloan
spring.main.allow-bean-definition-overriding=true
management.endpoints.web.exposure.include=*
spring.codec.max-in-memory-size=16
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG1
#-------------------------------------------
spring.datasource.url = jdbc:postgresql://192.168.2.47:5432/grameenkoota
spring.datasource.username=grameenkoota
spring.datasource.password=N8HHXVjsM8FYyR0dmpUOM+ta+mlj1FpIBO/HOBmzw6mX3yWBgb5lkrTUTkasTvRu
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.maximum-pool-size=10
spring.datasource.minimum-idle=5
spring.datasource.maxLifeTime=30000
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG2
#-------------------------------------------
apz.datasource.url = jdbc:postgresql://192.168.2.47:5432/grameenkoota
apz.datasource.username = grameenkoota
apz.datasource.password = N8HHXVjsM8FYyR0dmpUOM+ta+mlj1FpIBO/HOBmzw6mX3yWBgb5lkrTUTkasTvRu
apz.datasource.driverClassName = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

apz.datasource.maximum-pool-size=5
apz.datasource.minimum-idle=2
apz.datasource.maxLifeTime=30000
#-------------------------------------------
#-------------------------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
#----------------------------------------------
spring.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.ddlAuto=none
spring.jpa.properties.showSQL=true
spring.jpa.properties.formatSQL=true
spring.datasource.maximumPoolSize=5
spring.datasource.minimumIdle=2
spring.datasource.poolName=CAGL-POSTGRE-GRAMEEN
spring.datasource.idleTimeOut=30000

apz.datasource.hikari.maximum-pool-size=10
apz.datasource.hikari.minimum-idle=2
apz.datasource.hikari.pool-name=CAGL-APPZILLONCB

apz.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
apz.jpa.properties.ddlAuto=none
apz.jpa.properties.showSQL=true
apz.jpa.properties.formatSQL=true
apz.datasource.maximumPoolSize=5
apz.datasource.minimumIdle=2
apz.datasource.poolName=CAGL-POSTGRE-APPZILLONCB
apz.datasource.idleTimeOut=30000
#------------------------------------------------
#Logging
#--------------------------------------------------
logging.level.com.iexceed.appzillonbanking.cagl.*=DEBUG
logging.file.name=/opt/loan/logs/loan.log
logging.logback.rollingpolicy.file-name-pattern=/opt/loan/logs/loan-%d{yyyy-MM-dd}.%i.log
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=200
logging.logback.rollingpolicy.clean-history-on-start=false

ab.common.interFaceJSONDir=/opt/loan/interfaces/
ab.common.externalServiceURLPath=/opt/loan/interfaces/ExternalServiceURL.json
ab.common.reportsTemplateDir=/opt/loan/report_templates/
ab.common.reportsOutputDir=/opt/loan/report_output/sanction

#ab.common.interFaceJSONDir=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Interfaces/
#ab.common.externalServiceURLPath=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Interfaces/ExternalServiceURL.json
#ab.common.reportsTemplateDir=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Reports/
#ab.common.reportsOutputDir=D:/GRAMMIN\ KOTA/CAGL/ReportsOuput/Sanction


litFilePath=/opt/loan/resources/COB\ LITCODES_
cobFlags=/opt/loan/resources/COB\ FLAGS.properties
litFileFormat=csv
litCodeFilePath=/opt/loan/resources/ONBOARDING_

#litFilePath=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/COB\ LITCODES_
#cobFlags=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/COB\ FLAGS.properties
#litFileFormat=csv
#litCodeFilePath=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/ONBOARDING_


ab.common.numOfRecordsInWidget=25
ab.common.numOfDaysRecords=25
ab.common.accountSTP=Y
ab.common.depositSTP=N
ab.common.cardSTP=N
ab.common.loanSTP=N


# Show why request binding failed
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
logging.level.org.springframework.web.reactive=DEBUG

# Show JSON parse errors
logging.level.com.fasterxml.jackson=DEBUG
